### ISSUE TITLE
Porting BLE Library to MSP432 Red

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp432r-core#38]
This is a continuation of #10. 

The BLE library used to work with release `5.23.1` but no longer with latest release `5.29.0`.

Building the example **SerialOverBLE** against the MSP432P401R fails with the following error:

```
In file included from /Users/ReiVilo/Documents/Projets/Energia/libraries/BLE/src/BLE.cpp:13:0:
/Users/ReiVilo/Documents/Projets/Energia/libraries/BLE/src/BLEBoard.h:16:44: fatal error: variants/MSP_EXP432P401R/Board.h: No such file or directory
 #include "variants/MSP_EXP432P401R/Board.h"
                                            ^
compilation terminated.
```

**Comment by StefanSch** [comment]
i think this should be solved in the library side, e.g. with

replace in BLEboard.h
#include "variants/MSP_EXP432P401R/Board.h"
with
#include "Board.h"

and delete
board.h

Does compile without errors (on windows)

**Comment by rei-vilo** [comment]
Thank you for the answer.

Yes, I did three changes:

+ Changed [BLEBoard.h:16](https://github.com/energia/ble_energia/blob/57ca9ebc164f0f5fc023e8b46c6829d9156f4b1a/BLE/src/BLEBoard.h#L16) `#include "variants/MSP_EXP432P401R/Board.h"` for `#include "Board.h"`

+ Removed [board.h](https://github.com/energia/ble_energia/blob/master/BLE/src/board.h)

+ Changed [BLEBoard.h:33](https://github.com/energia/ble_energia/blob/57ca9ebc164f0f5fc023e8b46c6829d9156f4b1a/BLE/src/BLEBoard.h#L33) `#define BLE_UART_ID        Board_UARTA2 // =1, USB Serial is Board_UARTA0=0` for `#define BLE_UART_ID        Serial1 // Board_UARTA2 // =1, USB Serial is Board_UARTA0=0`

The **SerialOverBLE** now builds. However, the CC2650 doesn't show up on the list of BLE devices of a BLE utility like nRF Connect.

**Comment by rei-vilo** [comment]
I refreshed the CC2650 with the default NP image, as it was programmed with the specific version for the edX course [Real-Time Bluetooth Networks: Shape the World — MOOC edX UTAustinX UT.RTBN.12.01x](https://www.edx.org/course/real-time-bluetooth-networks-shape-the-world).

**Comment by rei-vilo** [comment]
I created the pull request https://github.com/ti-simplelink/ble_energia/pull/8 with the three fixes, after testing it on a MSP432P401R LaunchPad (red) with MSP432P401R board package 5.29.0.

@robertinant Feel free to validate it.
